name: CD(iOs)-HazardHunt

on:
  #workflow_run:
  #  workflows:
  #    - CI-HazardHunt
  #  types:
  #    - completed
  #  branches:
  #      - main
  #      - 15-konfiguroi-sovelluksen-frontend-käyttämään-expo-easia-sovelluksen-rakentamisessa
  push:
    branches:
      - 15-konfiguroi-sovelluksen-frontend-käyttämään-expo-easia-sovelluksen-rakentamisessa
  workflow_dispatch:

jobs:
  build:
    name: EAS Build and Submit
    runs-on: ubuntu-latest
    #if: >
    #  ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' }}  # Only deploy on successful builds triggered by push events
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}        
      - name: Create .env file
        run: echo "EAS_PROJECT_ID=${{ secrets.EAS_PROJECT_ID }}" > ./TTS/.env
      - name: Create eas.json with secrets
        run: |
          echo '{
            "cli": {
              "version": ">= 10.8.2",
              "appVersionSource": "remote"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "channel": "development"
              },
              "preview": {
                "distribution": "internal",
                "channel": "preview"
              },
              "production": {
                "autoIncrement": true,
                "channel": "production"
              }
            },
            "submit": {
              "production": {
                "ios": {
                  "appleId": "'"${{ secrets.EAS_APPLE_ID }}"'",
                  "ascAppId": "'"${{ secrets.EAS_ASC_APP_ID }}"'",
                  "appleTeamId": "'"${{ secrets.EAS_APPLE_TEAM_ID }}"'"
                }
              }
            }
          }' > ./TTS/eas.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./TTS
      - name: Build on EAS
        run: dotenv -c -- eas build -p ios --non-interactive --no-wait --profile production --auto-submit
        working-directory: ./TTS
        env:
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
      - name: Remove .env file
        run: rm ./TTS/.env
      - name: Remove eas.json file
        run: rm ./TTS/eas.json
      