name: CD-HazardHunt-UAT

on:
  workflow_dispatch:

jobs:
  build:
    name: EAS Build and Submit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_EAS_PROJECT_ID=${{ secrets.EAS_PROJECT_ID }}" > ./TTS/.env
          echo "ENVIRONMENT=uat" >> ./TTS/.env

      - name: Create eas.json with secrets
        run: |
          echo '{
            "cli": {
              "version": ">= 10.8.2",
              "appVersionSource": "remote"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "channel": "development"
              },
              "preview": {
                "distribution": "internal",
                "channel": "preview"
              },
              "production": {
                "autoIncrement": true,
                "channel": "production"
              }
            },
            "submit": {
              "production": {
                "ios": {
                  "appleId": "${{ secrets.EAS_APPLE_ID }}",
                  "ascAppId": "${{ secrets.EAS_ASC_APP_ID }}",
                  "appleTeamId": "${{ secrets.EAS_APPLE_TEAM_ID }}"
                },
                "android": {
                  "track": "internal",
                  "releaseStatus": "draft",
                  "changesNotSentForReview": true
                }
              }
            }
          }' > ./TTS/eas.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./TTS

      - name: Build on EAS
        run: dotenv -- eas build -p all --non-interactive --no-wait --profile production --auto-submit
        working-directory: ./TTS
        env:
          EXPO_PUBLIC_EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
          ENVIRONMENT: uat


      - name: Remove .env file
        run: rm ./TTS/.env

      - name: Remove eas.json file
        run: rm ./TTS/eas.json